export * from './collection.service';
import { CollectionService } from './collection.service';
export * from './competition.service';
import { CompetitionService } from './competition.service';
export * from './competitionRun.service';
import { CompetitionRunService } from './competitionRun.service';
export * from './competitionRunAdmin.service';
import { CompetitionRunAdminService } from './competitionRunAdmin.service';
export * from './judgement.service';
import { JudgementService } from './judgement.service';
export * from './log.service';
import { LogService } from './log.service';
export * from './submission.service';
import { SubmissionService } from './submission.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [CollectionService, CompetitionService, CompetitionRunService, CompetitionRunAdminService, JudgementService, LogService, SubmissionService, UserService];
