#!/bin/sh

. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Inspired by https://stackoverflow.com/a/16853458

CHANGED=`git diff $1 $2 --stat -- doc/oas.json | wc -l `
if [ $CHANGED -gt 0 ];
then
  echo "OpenApi specifications changed. Regenerating client bindings."
  ./gradlew openApiGenerate
else
  echo "OpenApi specifications not changed."
fi
