import { ServerMessageType } from './server-message-type.enum';
import ServerMessageTypeEnum = ServerMessageType.ServerMessageTypeEnum;
import { IWsMessage } from './ws-message.interface';
import { ApiEvaluationState } from '../../../../openapi/model/apiEvaluationState';
import { ApiEvaluationOverview } from '../../../../openapi/model/apiEvaluationOverview';
import { ApiTeamTaskOverview } from '../../../../openapi/model/apiTeamTaskOverview';

/**
 * Structure of a ServerMessage as generated by the DRES server.
 *
 * When state, overview or teamOverview are present, consumers should apply them directly
 * to their local state instead of issuing a separate HTTP request.
 */
export interface IWsServerMessage extends IWsMessage {
  evaluationId: string;
  taskId?: string;
  type: ServerMessageTypeEnum;
  timestamp: number;
  /** Embedded evaluation state diff. Present on TASK_START, TASK_END. */
  state?: ApiEvaluationState;
  /** Embedded evaluation overview diff. Present on TASK_START, TASK_END, COMPETITION_UPDATE. */
  overview?: ApiEvaluationOverview;
  /** Embedded single-team overview diff. Present on TASK_UPDATED (submissions); scoped to the submitting team. */
  teamOverview?: ApiTeamTaskOverview;
}
