import {ServerMessageType} from './server-message-type.enum';
import ServerMessageTypeEnum = ServerMessageType.ServerMessageTypeEnum;
import {IWsMessage} from './ws-message.interface';

/**
 * Structure of a ServerMessage as generated by the DRES server.
 */
export interface IWsServerMessage extends IWsMessage {
    runId: number;
    type: ServerMessageTypeEnum;
    timestamp: number;
}
