/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CachedVideoItem } from './cachedVideoItem';
import { TaskDescription } from './taskDescription';
import { TaskType } from './taskType';
import { Team } from './team';
import { TaskGroup } from './taskGroup';


export interface CompetitionDescription { 
    id: number;
    name: string;
    description?: string;
    taskTypes: Array<TaskType>;
    groups: Array<TaskGroup>;
    tasks: Array<TaskDescription>;
    teams: Array<Team>;
    uid: string;
    allCachedVideoItems: Array<CachedVideoItem>;
}

