/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfiguredOptionOptions { 
    option: ConfiguredOptionOptions.OptionEnum;
    parameters: { [key: string]: string; };
}
export namespace ConfiguredOptionOptions {
    export type OptionEnum = 'HIDDEN_RESULTS' | 'MAP_TO_SEGMENT';
    export const OptionEnum = {
        HiddenResults: 'HIDDEN_RESULTS' as OptionEnum,
        MapToSegment: 'MAP_TO_SEGMENT' as OptionEnum
    };
}


