/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfiguredOptionQueryComponentType { 
    option: ConfiguredOptionQueryComponentType.OptionEnum;
    parameters: { [key: string]: string; };
}
export namespace ConfiguredOptionQueryComponentType {
    export type OptionEnum = 'IMAGE_ITEM' | 'VIDEO_ITEM_SEGMENT' | 'TEXT' | 'EXTERNAL_IMAGE' | 'EXTERNAL_VIDEO';
    export const OptionEnum = {
        IMAGE_ITEM: 'IMAGE_ITEM' as OptionEnum,
        VIDEO_ITEM_SEGMENT: 'VIDEO_ITEM_SEGMENT' as OptionEnum,
        TEXT: 'TEXT' as OptionEnum,
        EXTERNAL_IMAGE: 'EXTERNAL_IMAGE' as OptionEnum,
        EXTERNAL_VIDEO: 'EXTERNAL_VIDEO' as OptionEnum
    };
}


