/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfiguredOptionSubmissionFilterType { 
    option: ConfiguredOptionSubmissionFilterType.OptionEnum;
    parameters: { [key: string]: string; };
}
export namespace ConfiguredOptionSubmissionFilterType {
    export type OptionEnum = 'NO_DUPLICATES' | 'LIMIT_CORRECT_PER_TEAM' | 'LIMIT_WRONG_PER_TEAM' | 'LIMIT_TOTAL_PER_TEAM' | 'LIMIT_CORRECT_PER_MEMBER' | 'TEMPORAL_SUBMISSION';
    export const OptionEnum = {
        NODUPLICATES: 'NO_DUPLICATES' as OptionEnum,
        LIMITCORRECTPERTEAM: 'LIMIT_CORRECT_PER_TEAM' as OptionEnum,
        LIMITWRONGPERTEAM: 'LIMIT_WRONG_PER_TEAM' as OptionEnum,
        LIMITTOTALPERTEAM: 'LIMIT_TOTAL_PER_TEAM' as OptionEnum,
        LIMITCORRECTPERMEMBER: 'LIMIT_CORRECT_PER_MEMBER' as OptionEnum,
        TEMPORALSUBMISSION: 'TEMPORAL_SUBMISSION' as OptionEnum
    };
}


