/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfiguredOptionTargetType { 
    option: ConfiguredOptionTargetType.OptionEnum;
    parameters: { [key: string]: string; };
}
export namespace ConfiguredOptionTargetType {
    export type OptionEnum = 'SINGLE_MEDIA_ITEM' | 'SINGLE_MEDIA_SEGMENT' | 'MULTIPLE_MEDIA_ITEMS' | 'JUDGEMENT';
    export const OptionEnum = {
        SingleMediaItem: 'SINGLE_MEDIA_ITEM' as OptionEnum,
        SingleMediaSegment: 'SINGLE_MEDIA_SEGMENT' as OptionEnum,
        MultipleMediaItems: 'MULTIPLE_MEDIA_ITEMS' as OptionEnum,
        Judgement: 'JUDGEMENT' as OptionEnum
    };
}


