/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfiguredOptionScoringType { 
    option: ConfiguredOptionScoringType.OptionEnum;
    parameters: { [key: string]: string; };
}
export namespace ConfiguredOptionScoringType {
    export type OptionEnum = 'KIS' | 'AVS';
    export const OptionEnum = {
        Kis: 'KIS' as OptionEnum,
        Avs: 'AVS' as OptionEnum
    };
}


