/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalVideoTaskDescriptionHintAllOf } from './externalVideoTaskDescriptionHintAllOf';
import { ExternalImageTaskDescriptionHintAllOfImageLocation } from './externalImageTaskDescriptionHintAllOfImageLocation';
import { TaskDescriptionHint } from './taskDescriptionHint';


export interface ExternalVideoTaskDescriptionHint { 
    videoLocation: ExternalImageTaskDescriptionHintAllOfImageLocation;
}
export namespace ExternalVideoTaskDescriptionHint {
}


