/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskRun } from './taskRun';
import { Submission } from './submission';
import { MediaItem } from './mediaItem';


export interface ItemSubmission extends Submission { 
}
export namespace ItemSubmission {
}


