/**
 * 
 * DRES API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemporalRange } from './temporalRange';
import { VideoItem } from './videoItem';


export interface KisTextualTaskDescription { 
    item: VideoItem;
    temporalRange: TemporalRange;
    descriptions: Array<string>;
    delay: number;
}

