/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaItem { 
    name: string;
    location: string;
    collection_1rSl5jE: string;
    id_1rSl5jE: string;
    id_Fwp7XY8?: string;
}

