/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QueryDescription { 
    taskName: string;
    taskType: QueryDescription.TaskTypeEnum;
    contentType: QueryDescription.ContentTypeEnum;
    payload: string;
}
export namespace QueryDescription {
    export type TaskTypeEnum = 'KIS_VISUAL' | 'KIS_TEXTUAL' | 'AVS';
    export const TaskTypeEnum = {
        KISVISUAL: 'KIS_VISUAL' as TaskTypeEnum,
        KISTEXTUAL: 'KIS_TEXTUAL' as TaskTypeEnum,
        AVS: 'AVS' as TaskTypeEnum
    };
    export type ContentTypeEnum = 'BINARY' | 'TEXT';
    export const ContentTypeEnum = {
        BINARY: 'BINARY' as ContentTypeEnum,
        TEXT: 'TEXT' as ContentTypeEnum
    };
}


