/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QueryDescription { 
    type: QueryDescription.TypeEnum;
}
export namespace QueryDescription {
    export type TypeEnum = 'VIDEO' | 'IMAGE' | 'TEXT';
    export const TypeEnum = {
        VIDEO: 'VIDEO' as TypeEnum,
        IMAGE: 'IMAGE' as TypeEnum,
        TEXT: 'TEXT' as TypeEnum
    };
}


