/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmissionInfo } from './submissionInfo';
import { RestPrepareJudgementAuditLogEntryAllOf } from './restPrepareJudgementAuditLogEntryAllOf';
import { RestAuditLogEntry } from './restAuditLogEntry';


export interface RestPrepareJudgementAuditLogEntry { 
    validator: string;
    token: string;
    submission: SubmissionInfo;
}
export namespace RestPrepareJudgementAuditLogEntry {
}


