/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskType } from './taskType';
import { Team } from './team';
import { TaskGroup } from './taskGroup';
import { RestTaskDescription } from './restTaskDescription';


export interface RestCompetitionDescription { 
    id: string;
    name: string;
    description?: string;
    taskTypes: Array<TaskType>;
    groups: Array<TaskGroup>;
    tasks: Array<RestTaskDescription>;
    teams: Array<Team>;
}

