/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmissionInfo } from './submissionInfo';
import { RestSubmissionAuditLogEntryAllOf } from './restSubmissionAuditLogEntryAllOf';
import { RestAuditLogEntry } from './restAuditLogEntry';


export interface RestSubmissionAuditLogEntry { 
    type: RestSubmissionAuditLogEntry.TypeEnum;
    id: string;
    timestamp: number;
    competition: string;
    taskName: string;
    submission: SubmissionInfo;
    api: RestSubmissionAuditLogEntry.ApiEnum;
    user?: string;
    address: string;
}
export namespace RestSubmissionAuditLogEntry {
    export type TypeEnum = 'COMPETITION_START' | 'COMPETITION_END' | 'TASK_START' | 'TASK_MODIFIED' | 'TASK_END' | 'SUBMISSION' | 'PREPARE_JUDGEMENT' | 'JUDGEMENT' | 'LOGIN' | 'LOGOUT';
    export const TypeEnum = {
        COMPETITIONSTART: 'COMPETITION_START' as TypeEnum,
        COMPETITIONEND: 'COMPETITION_END' as TypeEnum,
        TASKSTART: 'TASK_START' as TypeEnum,
        TASKMODIFIED: 'TASK_MODIFIED' as TypeEnum,
        TASKEND: 'TASK_END' as TypeEnum,
        SUBMISSION: 'SUBMISSION' as TypeEnum,
        PREPAREJUDGEMENT: 'PREPARE_JUDGEMENT' as TypeEnum,
        JUDGEMENT: 'JUDGEMENT' as TypeEnum,
        LOGIN: 'LOGIN' as TypeEnum,
        LOGOUT: 'LOGOUT' as TypeEnum
    };
    export type ApiEnum = 'REST' | 'CLI' | 'INTERNAL';
    export const ApiEnum = {
        REST: 'REST' as ApiEnum,
        CLI: 'CLI' as ApiEnum,
        INTERNAL: 'INTERNAL' as ApiEnum
    };
}


