/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestTaskDescriptionTargetItem } from './restTaskDescriptionTargetItem';


export interface RestTaskDescriptionTarget { 
    type: RestTaskDescriptionTarget.TypeEnum;
    mediaItems: Array<RestTaskDescriptionTargetItem>;
}
export namespace RestTaskDescriptionTarget {
    export type TypeEnum = 'SINGLE_MEDIA_ITEM' | 'SINGLE_MEDIA_SEGMENT' | 'MULTIPLE_MEDIA_ITEMS' | 'JUDGEMENT';
    export const TypeEnum = {
        SingleMediaItem: 'SINGLE_MEDIA_ITEM' as TypeEnum,
        SingleMediaSegment: 'SINGLE_MEDIA_SEGMENT' as TypeEnum,
        MultipleMediaItems: 'MULTIPLE_MEDIA_ITEMS' as TypeEnum,
        Judgement: 'JUDGEMENT' as TypeEnum
    };
}


