/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RestMediaItem { 
    id: string;
    name: string;
    type: RestMediaItem.TypeEnum;
    collectionId: string;
    durationMs?: number;
    fps?: number;
}
export namespace RestMediaItem {
    export type TypeEnum = 'IMAGE' | 'VIDEO';
    export const TypeEnum = {
        IMAGE: 'IMAGE' as TypeEnum,
        VIDEO: 'VIDEO' as TypeEnum
    };
}


