/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestAuditLogEntry } from './restAuditLogEntry';
import { RestJudgementAuditLogEntryAllOf } from './restJudgementAuditLogEntryAllOf';


export interface RestJudgementAuditLogEntry { 
    competition: string;
    validator: string;
    token: string;
    verdict: RestJudgementAuditLogEntry.VerdictEnum;
    api: RestJudgementAuditLogEntry.ApiEnum;
    user?: string;
}
export namespace RestJudgementAuditLogEntry {
    export type VerdictEnum = 'CORRECT' | 'WRONG' | 'INDETERMINATE' | 'UNDECIDABLE';
    export const VerdictEnum = {
        CORRECT: 'CORRECT' as VerdictEnum,
        WRONG: 'WRONG' as VerdictEnum,
        INDETERMINATE: 'INDETERMINATE' as VerdictEnum,
        UNDECIDABLE: 'UNDECIDABLE' as VerdictEnum
    };
    export type ApiEnum = 'REST' | 'CLI' | 'INTERNAL';
    export const ApiEnum = {
        REST: 'REST' as ApiEnum,
        CLI: 'CLI' as ApiEnum,
        INTERNAL: 'INTERNAL' as ApiEnum
    };
}


