/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestMediaItem } from './restMediaItem';


export interface SubmissionInfo { 
    id?: string;
    team: string;
    member: string;
    status: SubmissionInfo.StatusEnum;
    timestamp: number;
    item?: RestMediaItem;
    start?: number;
    end?: number;
}
export namespace SubmissionInfo {
    export type StatusEnum = 'CORRECT' | 'WRONG' | 'INDETERMINATE' | 'UNDECIDABLE';
    export const StatusEnum = {
        Correct: 'CORRECT' as StatusEnum,
        Wrong: 'WRONG' as StatusEnum,
        Indeterminate: 'INDETERMINATE' as StatusEnum,
        Undecidable: 'UNDECIDABLE' as StatusEnum
    };
}


