/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmissionAuditLogEntryAllOf } from './submissionAuditLogEntryAllOf';
import { AuditLogEntry } from './auditLogEntry';
import { Submission } from './submission';


export interface SubmissionAuditLogEntry { 
    taskName: string;
    submission: Submission;
    api: SubmissionAuditLogEntry.ApiEnum;
    user?: string;
    address: string;
    competition_1rSl5jE: string;
}
export namespace SubmissionAuditLogEntry {
    export type ApiEnum = 'REST' | 'CLI' | 'INTERNAL';
    export const ApiEnum = {
        REST: 'REST' as ApiEnum,
        CLI: 'CLI' as ApiEnum,
        INTERNAL: 'INTERNAL' as ApiEnum
    };
}


