/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskInfo { 
    name: string;
    taskGroup: string;
    type: TaskInfo.TypeEnum;
    duration: number;
}
export namespace TaskInfo {
    export type TypeEnum = 'KIS_VISUAL' | 'KIS_TEXTUAL' | 'AVS';
    export const TypeEnum = {
        KISVISUAL: 'KIS_VISUAL' as TypeEnum,
        KISTEXTUAL: 'KIS_TEXTUAL' as TypeEnum,
        AVS: 'AVS' as TypeEnum
    };
}


