/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {TaskType} from './taskType';
import {TaskDescriptionComponent} from './taskDescriptionComponent';
import {TaskGroup} from './taskGroup';


export interface TaskDescription { 
    id: string;
    name: string;
    taskGroup: TaskGroup;
    taskType: TaskType;
    duration: number;
    mediaCollectionId: string;
    components: Array<TaskDescriptionComponent>;
    target: object;
}

