/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskType } from './taskType';
import { TaskDescriptionHint } from './taskDescriptionHint';
import { TaskGroup } from './taskGroup';
import { TaskDescriptionTarget } from './taskDescriptionTarget';


export interface TaskDescription { 
    name: string;
    taskGroup: TaskGroup;
    taskType: TaskType;
    duration: number;
    target: TaskDescriptionTarget;
    hints: Array<TaskDescriptionHint>;
    mediaCollectionId_1rSl5jE: string;
    id_1rSl5jE: string;
}

