/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskDescriptionHint { 
    contentType?: TaskDescriptionHint.ContentTypeEnum;
    ordinal: number;
    contentType$backend: TaskDescriptionHint.ContentTypebackendEnum;
    start?: number;
    end?: number;
}
export namespace TaskDescriptionHint {
    export type ContentTypeEnum = 'TEXT' | 'VIDEO' | 'IMAGE';
    export const ContentTypeEnum = {
        TEXT: 'TEXT' as ContentTypeEnum,
        VIDEO: 'VIDEO' as ContentTypeEnum,
        IMAGE: 'IMAGE' as ContentTypeEnum
    };
    export type ContentTypebackendEnum = 'TEXT' | 'VIDEO' | 'IMAGE';
    export const ContentTypebackendEnum = {
        TEXT: 'TEXT' as ContentTypebackendEnum,
        VIDEO: 'VIDEO' as ContentTypebackendEnum,
        IMAGE: 'IMAGE' as ContentTypebackendEnum
    };
}


