/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskDescription { 
    taskType: TaskDescription.TaskTypeEnum;
}
export namespace TaskDescription {
    export type TaskTypeEnum = 'KIS_VISUAL' | 'KIS_TEXTUAL' | 'AVS';
    export const TaskTypeEnum = {
        KISVISUAL: 'KIS_VISUAL' as TaskTypeEnum,
        KISTEXTUAL: 'KIS_TEXTUAL' as TaskTypeEnum,
        AVS: 'AVS' as TaskTypeEnum
    };
}


