/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Submission } from './submission';
import { TaskDescription } from './taskDescription';


export interface TaskRun { 
    submissions: Array<Submission>;
    task: TaskDescription;
    filter: object;
    scorer: object;
    validator: object;
    started?: number;
    ended?: number;
    duration: number;
    uid_1rSl5jE: string;
    taskId_1rSl5jE: string;
    hasStarted?: boolean;
    hasEnded?: boolean;
    running?: boolean;
    position: number;
}

