/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfiguredOptionOptions } from './configuredOptionOptions';
import { ConfiguredOptionQueryComponentType } from './configuredOptionQueryComponentType';
import { ConfiguredOptionScoringType } from './configuredOptionScoringType';
import { ConfiguredOptionSubmissionFilterType } from './configuredOptionSubmissionFilterType';
import { ConfiguredOptionTargetType } from './configuredOptionTargetType';


export interface TaskType { 
    name: string;
    taskDuration: number;
    targetType: ConfiguredOptionTargetType;
    components: Array<ConfiguredOptionQueryComponentType>;
    score: ConfiguredOptionScoringType;
    filter: Array<ConfiguredOptionSubmissionFilterType>;
    options: Array<ConfiguredOptionOptions>;
}

