/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {QueryDescription} from './queryDescription';
import {TextualDescription} from './textualDescription';


export interface TextQueryDescription extends QueryDescription { 
    taskName: string;
    text: Array<TextualDescription>;
    video?: string;
    contentType?: string;
}
export namespace TextQueryDescription {
}


