# A workflow to use https://github.com/marketplace/actions/fixed-issues-labeler

name: Label Closed Issues on Branches

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: gh-bot/fix-labeler@v2
